/**
	* @swagger
	* /users/nickname-check:
	*   post:
	*     summary: Register a new user
	*     tags:
	*        - user
	*     security: []
	*     requestBody:
	*       required: true
	*       content:
	*         application/json:
	*           schema:
	*             properties:
	*               name:
	*                 type: string
	*                 description: desc
	*                 example: abc
	*/
router.get('/user/nickname-check', getList);
